name: monte_carlo_sims
description: A basic Monte Carlo image integration app.
author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  setalpha: ^0.9.3

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
